import gql from 'graphql-tag';
import { DocumentNode } from 'graphql';

export const adminApiExtensions: DocumentNode = gql`
    type SellerRegistrationResult {
        channel: Channel!
        "Shown once, in this response only — never logged or persisted in plaintext."
        temporaryPassword: String!
    }

    input OnboardSellerInput {
        "The id of a pre-existing Seller (created via the native Sellers > New Seller screen) to provision marketplace infrastructure for."
        sellerId: ID!
        "Becomes Channel.code AND Channel.token. Optional — set explicitly to match a pre-coordinated AtroPIM Channel code so pim-sync can populate this seller's catalog; if omitted, a random token is generated."
        token: String
        sellerEmail: String!
        shippingPreferenceNote: String
    }

    extend type Mutation {
        "Provisions Channel + Role + Administrator + StockLocation for an existing Seller. Fails if the Seller already has an associated Channel. Does not assign any ShippingMethod/PaymentMethod — that remains a manual admin step via native channel-assignment screens."
        onboardSeller(input: OnboardSellerInput!): SellerRegistrationResult!
        "Marks the given Seller Orders' payoutStatus as paid."
        markPayoutsPaid(orderIds: [ID!]!): [Order!]!
    }

    extend type Seller {
        "The Channel(s) provisioned for this Seller via onboardSeller, if any. Empty until onboarding has happened."
        channels: [Channel!]!
    }
`;

export const shopApiExtensions: DocumentNode = gql`
    type SellerRegistrationResult {
        channel: Channel!
        "Shown once, in this response only — never logged or persisted in plaintext."
        temporaryPassword: String!
    }

    input RegisterSellerInput {
        shopName: String!
        sellerEmail: String!
        shippingPreferenceNote: String
    }

    extend type Mutation {
        "Public self-service seller onboarding. Immediately creates the seller's Channel/Role/Administrator — there is no approval/moderation step yet."
        registerNewSeller(input: RegisterSellerInput!): SellerRegistrationResult!
    }

    extend type Query {
        """
        The current Customer's own order history — the Aggregate Order (or Regular Order, for
        purchases that were never split) for each purchase, one row per checkout. Excludes the
        internal per-seller Orders that a multi-vendor checkout splits off
        (OrderType.Seller) — those are never something the customer chose to place, only
        internal bookkeeping generated by the platform. Use this instead of
        activeCustomer.orders/Customer.orders on the storefront: that field also returns
        Seller Orders (they're assigned to the default Channel too, alongside the customer's
        own), which duplicates a single purchase into N+1 rows in an order-history list.
        """
        myOrders(options: OrderListOptions): OrderList!
    }
`;
