import {MigrationInterface, QueryRunner} from "typeorm";

/**
 * Stage 2 — cms, pim-sync, quote-plugin, multivendor-plugin.
 *
 * All statements were generated by `vendure migrate -g` EXCEPT the
 * `IDX_product_customFieldsMpn` index, which is hand-written (see below).
 *
 * ## WARNING: this migration causes generator drift
 *
 * Vendure's custom field config supports `unique` but has no `index` option, so
 * there is no declarative way to index `customFieldsMpn`. The index is created
 * here by hand, which means TypeORM's entity metadata does not know it exists.
 *
 * Consequence: **every future `npx vendure migrate -g` will emit a spurious
 * `DROP INDEX "IDX_product_customFieldsMpn"`.** Delete that line from the
 * generated file before running it, or the PIM sync silently loses its index and
 * degrades to a sequential scan on every product lookup.
 *
 * This is not a new problem — agx-stores hit it twice
 * (`1783342397265-add-address-geo-coordinates.ts` and
 * `1783706331881-add-quote-status-fields.ts` both had to be hand-trimmed).
 * It is reproduced here deliberately: the index matters more on the sync path
 * than the migration inconvenience costs. See docs/plugins/pim-sync.md.
 */
export class Stage2CmsPimQuoteMultivendor1788352280095 implements MigrationInterface {

   public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "quote_sequence" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "year" integer NOT NULL, "lastValue" integer NOT NULL DEFAULT '0', "id" SERIAL NOT NULL, "channelId" integer NOT NULL, CONSTRAINT "UQ_f107310396e81613bd0feec1563" UNIQUE ("channelId", "year"), CONSTRAINT "PK_0985d703eac571ebae9e02b9e2f" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`ALTER TABLE "product_translation" ADD "customFieldsDetail" text`, undefined);
        await queryRunner.query(`ALTER TABLE "product_translation" ADD "customFieldsSpecification" text`, undefined);
        await queryRunner.query(`ALTER TABLE "product_translation" ADD "customFieldsSeotitle" character varying(255)`, undefined);
        await queryRunner.query(`ALTER TABLE "product_translation" ADD "customFieldsSeodescription" character varying(255)`, undefined);
        await queryRunner.query(`ALTER TABLE "product" ADD "customFieldsMpn" character varying(255)`, undefined);
        // HAND-WRITTEN — not produced by the generator. See the class comment above.
        await queryRunner.query(`CREATE INDEX "IDX_product_customFieldsMpn" ON "product" ("customFieldsMpn")`, undefined);
        await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsQuotevaliduntil" TIMESTAMP(6)`, undefined);
        await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsQuotereference" character varying(255)`, undefined);
        await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsQuotenotes" text`, undefined);
        await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsQuoteacceptedat" TIMESTAMP(6)`, undefined);
        await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsQuotestatus" character varying(255)`, undefined);
        await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsQuoterequestedat" TIMESTAMP(6)`, undefined);
        await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsQuotesentat" TIMESTAMP(6)`, undefined);
        await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsQuoterevision" integer`, undefined);
        await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsPayoutstatus" character varying(255)`, undefined);
        await queryRunner.query(`ALTER TABLE "seller" ADD "customFieldsSelleronboardingnote" text`, undefined);
        await queryRunner.query(`ALTER TABLE "seller" ADD "customFieldsPlatformfeepercent" double precision NOT NULL DEFAULT '10'`, undefined);
   }

   public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "seller" DROP COLUMN "customFieldsPlatformfeepercent"`, undefined);
        await queryRunner.query(`ALTER TABLE "seller" DROP COLUMN "customFieldsSelleronboardingnote"`, undefined);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsPayoutstatus"`, undefined);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsQuoterevision"`, undefined);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsQuotesentat"`, undefined);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsQuoterequestedat"`, undefined);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsQuotestatus"`, undefined);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsQuoteacceptedat"`, undefined);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsQuotenotes"`, undefined);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsQuotereference"`, undefined);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsQuotevaliduntil"`, undefined);
        // HAND-WRITTEN — mirrors the CREATE INDEX in up().
        await queryRunner.query(`DROP INDEX "IDX_product_customFieldsMpn"`, undefined);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "customFieldsMpn"`, undefined);
        await queryRunner.query(`ALTER TABLE "product_translation" DROP COLUMN "customFieldsSeodescription"`, undefined);
        await queryRunner.query(`ALTER TABLE "product_translation" DROP COLUMN "customFieldsSeotitle"`, undefined);
        await queryRunner.query(`ALTER TABLE "product_translation" DROP COLUMN "customFieldsSpecification"`, undefined);
        await queryRunner.query(`ALTER TABLE "product_translation" DROP COLUMN "customFieldsDetail"`, undefined);
        await queryRunner.query(`DROP TABLE "quote_sequence"`, undefined);
   }

}
